// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: auth/auth.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "usercenter/api/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                      // 验证码
	CodeKey       string                 `protobuf:"bytes,4,opt,name=code_key,json=codeKey,proto3" json:"code_key,omitempty"` // 验证码关联的key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterRequest) GetCodeKey() string {
	if x != nil {
		return x.CodeKey
	}
	return ""
}

type LoginMobileRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Mobile string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// Types that are valid to be assigned to Credential:
	//
	//	*LoginMobileRequest_Password
	//	*LoginMobileRequest_Code
	//	*LoginMobileRequest_CodeKey
	Credential    isLoginMobileRequest_Credential `protobuf_oneof:"credential"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginMobileRequest) Reset() {
	*x = LoginMobileRequest{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMobileRequest) ProtoMessage() {}

func (x *LoginMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMobileRequest.ProtoReflect.Descriptor instead.
func (*LoginMobileRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginMobileRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginMobileRequest) GetCredential() isLoginMobileRequest_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *LoginMobileRequest) GetPassword() string {
	if x != nil {
		if x, ok := x.Credential.(*LoginMobileRequest_Password); ok {
			return x.Password
		}
	}
	return ""
}

func (x *LoginMobileRequest) GetCode() string {
	if x != nil {
		if x, ok := x.Credential.(*LoginMobileRequest_Code); ok {
			return x.Code
		}
	}
	return ""
}

func (x *LoginMobileRequest) GetCodeKey() string {
	if x != nil {
		if x, ok := x.Credential.(*LoginMobileRequest_CodeKey); ok {
			return x.CodeKey
		}
	}
	return ""
}

type isLoginMobileRequest_Credential interface {
	isLoginMobileRequest_Credential()
}

type LoginMobileRequest_Password struct {
	Password string `protobuf:"bytes,2,opt,name=password,proto3,oneof"`
}

type LoginMobileRequest_Code struct {
	Code string `protobuf:"bytes,3,opt,name=code,proto3,oneof"` // 验证码
}

type LoginMobileRequest_CodeKey struct {
	CodeKey string `protobuf:"bytes,4,opt,name=code_key,json=codeKey,proto3,oneof"` // 验证码关联的key
}

func (*LoginMobileRequest_Password) isLoginMobileRequest_Credential() {}

func (*LoginMobileRequest_Code) isLoginMobileRequest_Credential() {}

func (*LoginMobileRequest_CodeKey) isLoginMobileRequest_Credential() {}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *common.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetUser() *common.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ResetPwdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CodeKey       string                 `protobuf:"bytes,4,opt,name=code_key,json=codeKey,proto3" json:"code_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPwdRequest) Reset() {
	*x = ResetPwdRequest{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPwdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPwdRequest) ProtoMessage() {}

func (x *ResetPwdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPwdRequest.ProtoReflect.Descriptor instead.
func (*ResetPwdRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ResetPwdRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ResetPwdRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ResetPwdRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResetPwdRequest) GetCodeKey() string {
	if x != nil {
		return x.CodeKey
	}
	return ""
}

type ResetPwdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPwdResponse) Reset() {
	*x = ResetPwdResponse{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPwdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPwdResponse) ProtoMessage() {}

func (x *ResetPwdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPwdResponse.ProtoReflect.Descriptor instead.
func (*ResetPwdResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x0fusercenter.auth\x1a\x1cgoogle/api/annotations.proto\x1a\x13common/common.proto\"t\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x19\n" +
	"\bcode_key\x18\x04 \x01(\tR\acodeKey\"\x8b\x01\n" +
	"\x12LoginMobileRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1c\n" +
	"\bpassword\x18\x02 \x01(\tH\x00R\bpassword\x12\x14\n" +
	"\x04code\x18\x03 \x01(\tH\x00R\x04code\x12\x1b\n" +
	"\bcode_key\x18\x04 \x01(\tH\x00R\acodeKeyB\f\n" +
	"\n" +
	"credential\"\xa2\x01\n" +
	"\fAuthResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.usercenter.common.UserR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"{\n" +
	"\x0fResetPwdRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x19\n" +
	"\bcode_key\x18\x04 \x01(\tR\acodeKey\"\x12\n" +
	"\x10ResetPwdResponse2\xf2\x04\n" +
	"\vAuthService\x12x\n" +
	"\x10RegisterByMobile\x12 .usercenter.auth.RegisterRequest\x1a\x1d.usercenter.auth.AuthResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/auth/register/mobile\x12~\n" +
	"\x11LoginByMobileCode\x12#.usercenter.auth.LoginMobileRequest\x1a\x1d.usercenter.auth.AuthResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/auth/login/mobile_code\x12|\n" +
	"\x10LoginByMobilePwd\x12#.usercenter.auth.LoginMobileRequest\x1a\x1d.usercenter.auth.AuthResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/auth/login/mobile_pwd\x12q\n" +
	"\fRefreshToken\x12\x1f.usercenter.auth.RefreshRequest\x1a\x1d.usercenter.auth.AuthResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/auth/token/refresh\x12x\n" +
	"\rResetPassword\x12 .usercenter.auth.ResetPwdRequest\x1a!.usercenter.auth.ResetPwdResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/auth/password/resetB\x1aZ\x18usercenter/api/auth;authb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: usercenter.auth.RegisterRequest
	(*LoginMobileRequest)(nil), // 1: usercenter.auth.LoginMobileRequest
	(*AuthResponse)(nil),       // 2: usercenter.auth.AuthResponse
	(*RefreshRequest)(nil),     // 3: usercenter.auth.RefreshRequest
	(*ResetPwdRequest)(nil),    // 4: usercenter.auth.ResetPwdRequest
	(*ResetPwdResponse)(nil),   // 5: usercenter.auth.ResetPwdResponse
	(*common.User)(nil),        // 6: usercenter.common.User
}
var file_auth_auth_proto_depIdxs = []int32{
	6, // 0: usercenter.auth.AuthResponse.user:type_name -> usercenter.common.User
	0, // 1: usercenter.auth.AuthService.RegisterByMobile:input_type -> usercenter.auth.RegisterRequest
	1, // 2: usercenter.auth.AuthService.LoginByMobileCode:input_type -> usercenter.auth.LoginMobileRequest
	1, // 3: usercenter.auth.AuthService.LoginByMobilePwd:input_type -> usercenter.auth.LoginMobileRequest
	3, // 4: usercenter.auth.AuthService.RefreshToken:input_type -> usercenter.auth.RefreshRequest
	4, // 5: usercenter.auth.AuthService.ResetPassword:input_type -> usercenter.auth.ResetPwdRequest
	2, // 6: usercenter.auth.AuthService.RegisterByMobile:output_type -> usercenter.auth.AuthResponse
	2, // 7: usercenter.auth.AuthService.LoginByMobileCode:output_type -> usercenter.auth.AuthResponse
	2, // 8: usercenter.auth.AuthService.LoginByMobilePwd:output_type -> usercenter.auth.AuthResponse
	2, // 9: usercenter.auth.AuthService.RefreshToken:output_type -> usercenter.auth.AuthResponse
	5, // 10: usercenter.auth.AuthService.ResetPassword:output_type -> usercenter.auth.ResetPwdResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	file_auth_auth_proto_msgTypes[1].OneofWrappers = []any{
		(*LoginMobileRequest_Password)(nil),
		(*LoginMobileRequest_Code)(nil),
		(*LoginMobileRequest_CodeKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
